config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :profiles, only: [:index, :show, :new, :create, :edit, :update]
  resources :products , only: [:index, :show, :new, :create, :edit, :update] do
    resources :orders, only: [:show,:new, :create]
    get 'search', on: :collection
    resources :comments, only: [:create]
    post 'enable', on: :member
    post 'disable', on: :member
    get 'status', on: :member
  end
  get 'my_products', to: 'products#my_products'

  resources :orders, only:[:index] do
    resources :chats, only: [:create]
    post 'accept', on: :member
    post 'decline', on: :member
  end

  resources :companies, only: [:index, :show]
  resources :comments, only: [] do 
    resources :answers , only: [:create]
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :company
  belongs_to :user
  has_many :products, dependent: :destroy
  has_many :comments , dependent: :destroy
  has_many :order
  has_many :chats

  validates :name, :nick_name, :date_of_birth, 
            :department, :role, :cpf, presence: true
  validates :name, :nick_name, :department, :role,
             length: {maximum: 30, message: 'São permitidos no maximo 30 caracteres'}
  validates :cpf, uniqueness: true
  validate :cpf_valid

  def cpf_valid
    if cpf.present? && !CPF.valid?(cpf)
      errors.add(:cpf, 'não é válido')
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :update]

  def index
    @profile = Profile.find_by(user_id: current_user.id)
    @products = Product.where(profile: @profile)
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(params.require(:profile).permit(:name, :nick_name, :date_of_birth, :department, :role, :cpf))
    @profile.user_id = current_user.id
    @profile.company_id = current_user.company_id
    if @profile.save
      redirect_to profiles_path, notice: 'Cadastro efetuado com sucesso'
    else
      render :new
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.update(params.require(:profile).permit(:name, :nick_name, :date_of_birth, :department, :role, :cpf))
    if @profile.save
      redirect_to profiles_path, notice: 'Dados alterados com sucesso'
    else
      render :edit
    end
  end
end 

app/views/profiles/_form.html.erb
<ul>
  <% @profile.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
</ul>

<div>
  <%= form_with model: @profile, local:true do |f| %>
    <div>
      <div><%= f.label :name%></div>
      <div><%= f.text_field :name %></div>
    </div>
    <div>
      <div><%= f.label :nick_name %></div>
      <div><%= f.text_field :nick_name %></div>
    </div>
    <div>
      <div><%= f.label :date_of_birth %></div>
      <div><%= f.date_field :date_of_birth %></div>
    </div>
    <div>
      <div><%= f.label :department %></div>
      <div><%= f.text_field :department %></div>
    </div>
    <div>
      <div><%= f.label :role %></div>
      <div><%= f.text_field :role %></div>
    </div>
    <div>
      <div><%= f.label :cpf %></div>
      <div><%= f.text_field :cpf %></div>
    </div>
    <%= f.submit 'Salvar' %>
  <% end %>
</div>

app/views/profiles/_profile.html.erb
<dl>
  <dt><%= Company.human_attribute_name(:name)%></dt>
  <dd><%= @profile.company.name %></dd>
  <dt><%= Profile.human_attribute_name(:name) %></dt>
  <dd><%= @profile.name %></dd>
  <dt><%= Profile.human_attribute_name(:email) %></dt>
  <dd><%= current_user.email %></dd>
  <dt><%= Profile.human_attribute_name(:nick_name) %></dt>
  <dd><%= @profile.nick_name %></dd>
  <dt><%= Profile.human_attribute_name(:date_of_birth) %></dt>
  <dd><%= l @profile.date_of_birth %></dd>
  <dt><%= Profile.human_attribute_name(:department) %></dt>
  <dd><%= @profile.department %></dd>
  <dt><%= Profile.human_attribute_name(:role) %></dt>
  <dd><%= @profile.role %></dd>
  <dt><%= Profile.human_attribute_name(:cpf) %></dt>
  <dd><%= @profile.cpf %></dd>
</dl>

app/views/profiles/edit.html.erb
<h1>Editar dados</h1>

<%= render partial: 'form', locals: {profile: @profile} %>

<%= link_to 'Voltar', profiles_path %>

app/views/profiles/index.html.erb
<header>
  <h1>Meu perfil</h1>
</header>
<div id="container">
  <% if @profile.nil? %>
    <h3>Nenhum perfil cadastrado</h3><br>
      <h3>Para comprar ou vender produtos é necessario completar o cadastro</h3>
      <%= link_to 'Completar cadastro', new_profile_path %>
 
  <% else %>
  <div id="description">
    <h3>Agora você já pode cadastrar seus produtos na Loja</h3>
    <%= render @profile%>
    <%= link_to 'Editar dados', edit_profile_path(@profile) %>
    </div>
  <% end %>
</div>
<footer>
  <%= link_to 'Voltar', root_path %>
</footer>

app/views/profiles/new.html.erb
<h1>Cadastrar perfil</h1>

<%= render partial: 'form', locals: {profile: @profile} %>

<%= link_to 'Voltar', profiles_path %>