config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :profiles, only: [:index, :show, :new, :create, :edit, :update]
  resources :products , only: [:index, :show, :new, :create, :edit, :update] do
    resources :orders, only: [:show,:new, :create]
    get 'search', on: :collection
    resources :comments, only: [:create]
    post 'enable', on: :member
    post 'disable', on: :member
    get 'status', on: :member
  end
  get 'my_products', to: 'products#my_products'

  resources :orders, only:[:index] do
    resources :chats, only: [:create]
    post 'accept', on: :member
    post 'decline', on: :member
  end

  resources :companies, only: [:index, :show]
  resources :comments, only: [] do 
    resources :answers , only: [:create]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @companies = Company.all
  end
end

app/views/home/index.html.erb
<div id="g-home">
  <% if user_signed_in? %>
    <%= link_to 'Sair', destroy_user_session_path, method: :delete %>
  <header>
    <% if current_user.profile.present? %>
      <h2>Olá, <%= current_user.profile.name.capitalize %></h2>
    <% end %>
    <h2>Bem vindo ao Marketplace</h2>
  </header>
  
  <div class="nav">
    <ul>
      <li><%= link_to 'Meu perfil', profiles_path %></li>
      <li><%= link_to 'Loja', products_path %></li>
      <li><%= link_to 'Colaboradores cadastrados', companies_path %></li>
      <li><%= link_to 'Meus anuncios', my_products_path %></li>
      <li> <%= link_to 'Meus pedidos', orders_path %> </li>
    </ul>
  </div>
</div>

  <% else %>
    <nav class="nav">
      <h1>Marketplace</h1>
      <h3>Empresas cadastradas ate o momento</h3>
      <% @companies.each do |company| %>
        <%= company.name %>
      <% end %>
      <h3>
        <%= link_to 'Entrar', new_user_session_path %><br>
        <%= link_to 'Registrar-se', new_user_registration_path %>
      </h2>
    </nav>
  <% end %>