config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :profiles, only: [:index, :show, :new, :create, :edit, :update]
  resources :products , only: [:index, :show, :new, :create, :edit, :update] do
    resources :orders, only: [:show,:new, :create]
    get 'search', on: :collection
    resources :comments, only: [:create]
    post 'enable', on: :member
    post 'disable', on: :member
    get 'status', on: :member
  end
  get 'my_products', to: 'products#my_products'

  resources :orders, only:[:index] do
    resources :chats, only: [:create]
    post 'accept', on: :member
    post 'decline', on: :member
  end

  resources :companies, only: [:index, :show]
  resources :comments, only: [] do 
    resources :answers , only: [:create]
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :profile
  belongs_to :product
  has_many :chats

  enum status: {waiting:0, accept: 10, decline: 20}
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, only: [:index,:show, :new, :create]

  def index
    @orders = Order.where(profile_id: current_user.profile)
  end

  def show
    @product = Product.find(params[:product_id])
    @order = @product.order
  end

  def new
    @product = Product.find(params[:product_id])
    @order = Order.new
  end

  def create
    @product = Product.find(params[:product_id])
    @order = Order.new(order_params)
    @order.save
    @order.waiting!
    @product.disable!
    redirect_to @product, notice: 'Compra efetuada com sucesso, aguarde confirmação do vendedor'
  end

  def accept
    @order = Order.find(params[:id])
    @order.accept!
    @order.product.sold!
    redirect_to status_product_path(@order.product, @order), notice: 'Venda finalizada'
  end

  def decline
    @order = Order.find(params[:id])
    @order.decline!
    @order.product.enable!
    redirect_to status_product_path(@order.product, @order), notice: 'Venda recusada'
  end
  private

  def order_params
    params.require(:order).permit(:body).merge(profile_id: current_user.profile.id, product_id: @product.id)
  end
end

app/views/orders/index.html.erb
<h2>Meus pedidos</h2>
<% if @orders.blank?%>
  <h2>Não há pedidos</h2>
<% else %>
  <%  if @orders.waiting.present? %>
  <div>
    <h3>Pedidos aguardado confirmação do vendedor</h3>
    <% @orders.waiting.each do |order| %>
      <dl>
        <dt> <% Product.human_attribute_name(:name) %> </dt>
        <dd><%= order.product.name %></dd>
        <dt> <% Product.human_attribute_name(:price) %> </dt>
        <dd><%= number_to_currency order.product.price %></dd>
        <dt>Vendedor</dt>
        <dt><%= order.product.profile.name %></dt>
      </dl>
        <%= link_to 'Ver detalhes', product_order_path(order.product_id, order) %>
      <% end %>
    <% end %>

    <%  if @orders.accept.present? %>
      <h3>Pedidos finalizados</h3>
      <% @orders.accept.each do |order| %>
        <dl>
          <dt> <% Product.human_attribute_name(:name) %> </dt>
          <dd><%= order.product.name %></dd>
          <dt> <% Product.human_attribute_name(:price) %> </dt>
          <dd><%= number_to_currency order.product.price %></dd>
          <dt>Vendedor</dt>
          <dt><%= order.product.profile.name %></dt>
        </dl>
        <%= link_to 'Ver detalhes', product_order_path(order.product_id, order) %>
      <% end %>
    <% end %>

    <% if @orders.decline.present? %>
      <h3>Pedidos cancelados pelo vendedor</h3>
      <% @orders.decline.each do |order| %>
        <dl>
          <dt> <% Product.human_attribute_name(:name) %> </dt>
          <dd><%= order.product.name %></dd>
          <dt> <% Product.human_attribute_name(:price) %> </dt>
          <dd><%= number_to_currency order.product.price %></dd>
          <dt>Vendedor</dt>
          <dt><%= order.product.profile.name %></dt>
        </dl>
        <%= link_to 'Ver detalhes', product_order_path(order.product_id, order) %>
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to 'Voltar', root_path %>

app/views/orders/new.html.erb
<h2>Confira os detalhes do produto e depois confirme a compra</h2>
<h3>Dados do vendedor</h3>
<div>
  <dl>
    <dt><%= Profile.human_attribute_name(:name) %></dt>
    <dd><%= @product.profile.name %><</dd>
    <dt><%= Profile.human_attribute_name(:cpf) %></dt>
    <dd><%= @product.profile.cpf %></dd>
    <dt><%= Profile.human_attribute_name(:date_of_birth) %></dt>
    <dd><%= l @product.profile.date_of_birth %></dd>
    <dt><%= Profile.human_attribute_name(:department) %></dt>
    <dd><%= @product.profile.department %></dd>
    <dt><%= Profile.human_attribute_name(:role) %></dt>
    <dd><%= @product.profile.role %></dd>
  </dl>
</div>

<h3>Descrição do produto</h3>
<div>
  <dl>
    <dt><%= Product.human_attribute_name(:category) %></dt>
    <dd><%= @product.category %></dd>
    <dt><%= Product.human_attribute_name(:name) %></dt>
    <dd><%= @product.name %></dd>
    <dt><%= Product.human_attribute_name(:description) %></dt>
    <dd><%= @product.description %></dd>
    <dt><%= Product.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency @product.price %></dd>
  </dl>
</div>

<h3>Dados do comprador</h3>
<h3></h3>
<div>
  <dl>
    <dt><%= Profile.human_attribute_name(:name) %></dt>
    <dd><%= current_user.profile.name %></dd>
    <dt><%= Profile.human_attribute_name(:cpf) %></dt>
    <dd><%= current_user.profile.cpf %></dd>
    <dt><%= Profile.human_attribute_name(:date_of_birth) %></dt>
    <dd><%= l current_user.profile.date_of_birth %></dd>
    <dt><%= Profile.human_attribute_name(:department) %></dt>
    <dd><%= current_user.profile.department %></dd>
    <dt><%= Profile.human_attribute_name(:role) %></dt>
    <dd><%= current_user.profile.role %></dd>
  </dl>
</div>

<%= form_with model:[@product, @order], local:true do |f| %>
  <%= f.label :body, 'Observações' %> 
  <%= f.text_area :body %>
  <%= f.submit 'Finalizar compra' %>
<% end %>

<%= link_to 'Voltar', product_path(@product) %>

app/views/orders/show.html.erb
<h2>Confira os detalhes do produto</h2>

<% if @order.product.profile.user_id == current_user.id && @order.waiting? %>
  <%= link_to 'Confirmar venda', accept_order_path(@order), method: :post %>
  <%= link_to 'Cancelar venda', decline_order_path(@order), method: :post %>
<% end %>
<% if @order.waiting? %>
  <h2>Aguardando confirmação do vendedor</h2>
<% end %>

<% if @order.accept?%>
    <h2>Essa venda foi finalizada</h2>
<% end %>
<% if @order.decline? %>
  <h2>Essa venda foi cancelada pelo vendedor</h2>
<% end %>

<h3>Dados do vendedor</h3>
<div>
  <dl>
    <dt><%= Profile.human_attribute_name(:name) %></dt>
    <dd><%= @product.profile.name %></dd>
    <dt><%= Profile.human_attribute_name(:cpf) %></dt>
    <dd><%= @product.profile.cpf %></dd>
    <dt><%= Profile.human_attribute_name(:date_of_birth) %></dt>
    <dd><%= l @product.profile.date_of_birth %></dd>
    <dt><%= Profile.human_attribute_name(:department) %></dt>
    <dd><%= @product.profile.department %></dd>
    <dt><%= Profile.human_attribute_name(:role) %></dt>
    <dd><%= @product.profile.role %></dd>
  </dl>
</div>

<h3>Descrição do produto</h3>
<div>
  <dl>
    <dt><%= Product.human_attribute_name(:category) %></dt>
    <dd><%= @product.category %></dd>
    <dt><%= Product.human_attribute_name(:name) %></dt>
    <dd><%= @product.name %></dd>
    <dt><%= Product.human_attribute_name(:description) %></dt>
    <dd><%= @product.description %></dd>
    <dt><%= Product.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency @product.price %></dd>
  </dl>
</div>

<h3>Dados do comprador</h3>
<h3></h3>
<div>
  <dl>
    <dt><%= Profile.human_attribute_name(:name) %></dt>
    <dd><%= @order.profile.name %></dd>
    <dt><%= Profile.human_attribute_name(:cpf) %></dt>
    <dd><%= @order.profile.cpf %></dd>
    <dt><%= Profile.human_attribute_name(:date_of_birth) %></dt>
    <dd><%= l @order.profile.date_of_birth %></dd>
    <dt><%= Profile.human_attribute_name(:department) %></dt>
    <dd><%= @order.profile.department %></dd>
    <dt><%= Product.human_attribute_name(:role) %></dt>
    <dd><%= @order.profile.role %></dd>
  </dl>
</div>
<div>
<span>Observação: </span>sp
  <%= @order.body %>
</div><br>
<strong>Chat</strong>
<div id="comment-product">
  <% @order.chats.each do |chat| %>
    <div class="ac_box_top">
      <div class="ac_box_cont">
        <%= "Usuário:  #{chat.profile.name}" %><br>
        <%=  chat.body %><br>
      </div>
    </div>  
  <% end %>
</div>
<div>
  <%= form_with model: [@order, @order.chats.build], local:true do |f| %>
    <div><%= f.label :body, 'Chat' %></div>
    <div><%= f.text_field :body %></div>
    <div><%= f.submit 'Enviar' %></div>
<% end %>
</div>

<% if @product.profile == current_user.profile%>
<%= link_to 'Voltar', my_products_path %>
<% else %>
<%= link_to 'Voltar', orders_path %>
<% end %>