config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :profiles, only: [:index, :show, :new, :create, :edit, :update]
  resources :products , only: [:index, :show, :new, :create, :edit, :update] do
    resources :orders, only: [:show,:new, :create]
    get 'search', on: :collection
    resources :comments, only: [:create]
    post 'enable', on: :member
    post 'disable', on: :member
    get 'status', on: :member
  end
  get 'my_products', to: 'products#my_products'

  resources :orders, only:[:index] do
    resources :chats, only: [:create]
    post 'accept', on: :member
    post 'decline', on: :member
  end

  resources :companies, only: [:index, :show]
  resources :comments, only: [] do 
    resources :answers , only: [:create]
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :profile
  belongs_to :company
  has_many :comments, dependent: :destroy
  has_one :order
  has_one_attached :image

  enum status: {enable:0 , disable: 10, sold: 20, canceled: 30}

  validates :name, :description, :price, :category, presence:true
  validates :price, numericality: {greater_than: 0}
  validates :name, length: {maximum: 30, message: 'São permitidos no maximo 30 caracteres'}
  validates :description, length: {maximum: 150, message: 'São permitidos no maximo 150 caracteres'}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :upgrade, :my_products]

  def index
    @products = Product.where(company: current_user.company)
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new 
  end

  def create
    @product = Product.new(product_params)
    @product.company_id = current_user.company_id
    @product.profile_id = current_user.profile.id
    if @product.save
      redirect_to my_products_path, notice: 'Produto cadatrado com sucesso'
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    if @product.save
      redirect_to my_products_path, notice: 'Alteração feita com sucesso'
    else
      render :edit
    end
  end

  def search
    @products_company = Product.where(company: current_user.company)
    @products = @products_company.where('name || description || category LIKE ?', "%#{params[:q]}%")
  end

  def my_products
    @profile = Profile.find_by(user_id: current_user.id)
    @products_disable = Product.where(profile: @profile).where(status: :disable)
    @products_enable = Product.where(profile: @profile).where(status: :enable)
    @products_sold = Product.where(profile: @profile).where(status: :sold)
    @products_canceled = Product.where(profile: @profile).where(status: :canceled)
  end


  def enable
    @product = Product.find(params[:id])
    @product.enable!
    redirect_to my_products_path, notice: 'Anuncio reativado'
  end

  def disable
    @product = Product.find(params[:id])
    @product.canceled!
    redirect_to my_products_path, notice: 'Anuncio desativado'
  end
  
  def status
    @product = Product.find(params[:id])
    @order = @product.order
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :category, :image)
  end

end

app/views/products/_form.html.erb
<% @product.errors.full_messages.each do |message| %>
    <li><%= message %></li>
<% end %>

<%= form_with model: @product, local:true do |f| %>
    <div>
      <div><%= f.label :name %></div>
      <div><%= f.text_field :name %></div>
    </div>
    <div>
      <div><%= f.label :description %></div>
      <div><%= f.text_field :description %></div>
    </div>
    <div>
      <div><%= f.label :price %></div>
      <div><%= f.number_field :price %></div>
    </div>
    <div>
      <div><%= f.label :category %></div>
      <div><%= f.select :category, options_for_select([['Eletronicos'],['Esporte e Lazer'],
                                                      ['Móveis'],['Eletrodomesticos'],
                                                      ['Brinquedos e Bebês'],['Moda e Beleza']]), prompt:'Escolha uma opção' %>
      </div>
      <div>
        <div><%= f.label :image, 'Foto' %></div>
        <div><%= f.file_field :image %></div>
      </div>
    <%= f.submit 'Anunciar' %>
<% end %><br>

app/views/products/edit.html.erb
<h1>Atualizar anuncio</h1>

<%= render partial: 'form', locals: {product: @product} %>

<%= link_to 'Voltar', product_path(@product) %>

app/views/products/index.html.erb
<h1>Loja</h1>

<div>
  <p>Digite um nome ou categoria do produto</p>
  <%= form_with url: search_products_path, method: :get, local:true do|f| %>
    <%= f.label :q, 'Pesquisar produtos' %>
    <%= f.text_field :q %>
    <%= f.submit 'Pesquisar' %>
  <% end %>
</div>


<div>
  <% if @products.enable.present? %>
  <p>Produtos anunciados</p>
    <% @products.enable.each do |product| %>
      <dl>
        <dt><%= Product.human_attribute_name(:category) %></dt>
        <dd><%= product.category %></dd>
        <dt><%= Product.human_attribute_name(:name) %></dt>
        <dd><%= link_to product.name, product_path(product) %></dd>
        <dt><%= Product.human_attribute_name(:price) %></dt>
        <dd><%= product.category %></dd>
    </dl>
    <% end %>
  <% end %>
</div>

<footer> <%= link_to 'Voltar', root_path %> </footer>

app/views/products/my_products.html.erb
<div>
<% if @profile.nil? %>
  <h3>Para comprar ou vender produtos é necessario completar o cadastro</h3>
  <%= link_to 'Completar cadastro', new_profile_path %>
<% else %>
  <%= link_to 'Anunciar produtos', new_product_path %>
  <nav>
  <% if @products_enable.present? %>
    <h2>Produtos disponiveis para venda</h2>
      <% @products_enable.each do |product| %>
      <%= link_to 'Ver detalhes', product_path(product) %>
      <%= link_to 'Desativar anuncio', disable_product_path(product), method: :post %>
      <dl>
        <dt><%= Product.human_attribute_name(:category) %></dt>
        <dd><%= product.category %></dd>
        <dt><%= Product.human_attribute_name(:name) %> </dt>
        <dd><%= product.name %></dd>
        <dt><%= Product.human_attribute_name(:description) %> </dt>
        <dd><%= product.description %></dd>
        <dt><%= Product.human_attribute_name(:price) %></dt>
        <dd><%= number_to_currency product.price %></dd>
      </dl>      
      <% end %>
    <% end %>
  </nav>

  <nav>
    <% if @products_disable.present? %>
      <h2>Aguardando confirmação de venda</h2>
      <% @products_disable.each do |product_waiting| %>
        <%= link_to 'Ver detalhes', status_product_path(product_waiting, product_waiting.order) %>
        <dl>
          <dt>Comprador</dt>
          <dd><%= product_waiting.order.profile.name %>  </dd>
          <dt><%= Product.human_attribute_name(:name) %></dt>
          <dd><%= product_waiting.name %></dd>
        </dl>
      <% end %>
    <% end %>
  </nav>

  <nav>
    <% if @products_sold.present? %>
      <h2>Produtos vendidos</h2>
      <% @products_sold.each do |product_sold| %>
        <%= link_to 'Ver detalhes', status_product_path(product_sold, product_sold.order) %>
        <dl>
          <dt>Comprador</dt>
          <dd><%= product_sold.order.profile.name %>  </dd>
          <dt><%= Product.human_attribute_name(:name) %></dt>
          <dd><%= product_sold.name %></dd>
          <dt><%= Product.human_attribute_name(:category) %></dt>
          <dd><%= product_sold.category %></dd>
          <dt><%= Product.human_attribute_name(:name) %> </dt>
          <dd><%= product_sold.name %></dd>
          <dt><%= Product.human_attribute_name(:description) %> </dt>
          <dd><%= product_sold.description %></dd>
          <dt><%= Product.human_attribute_name(:price) %></dt>
          <dd><%= number_to_currency product_sold.price %></dd>
        </dl>
      <% end %>
    <% end %>
  </nav>

  <nav>
    <% if @products_canceled.present? %>
      <h2>Anuncio cancelado</h2>
      <% @products_canceled.each do |product_canceled| %>
        <%= link_to 'Ver detalhes', product_path(product_canceled) %>
        <%= link_to 'Reativar anuncio', enable_product_path(product_canceled), method: :post %>
        <dl>
        <dt><%= Product.human_attribute_name(:category) %></dt>
        <dd><%= product_canceled.category %></dd>
        <dt><%= Product.human_attribute_name(:name) %> </dt>
        <dd><%= product_canceled.name %></dd>
        <dt><%= Product.human_attribute_name(:description) %> </dt>
        <dd><%= product_canceled.description %></dd>
        <dt><%= Product.human_attribute_name(:price) %></dt>
        <dd><%= number_to_currency product_canceled.price %></dd>
      </dl>
      <% end %>
    <% end %>
  </nav>

<% end %>
</div>


<%= link_to 'Voltar', root_path %>

app/views/products/new.html.erb
<h1>Preencha o formulario para anunciar</h1>

<%= render partial: 'form', locals: {product: @product} %>

<%= link_to 'Ir para loja', products_path %>
<%= link_to 'Voltar para meus anuncios', my_products_path %>

app/views/products/search.html.erb
<h1>Resultado da pesquisa</h1>


<% @products.enable.each do |product| %>
  <div>
    <dl>
    <dt><%= Product.human_attribute_name(:category) %></dt>
    <dd><%= product.category %></dd>
    <dt><%= Product.human_attribute_name(:product) %></dt>
    <dd><%= link_to product.name, product_path(product) %></dd>
    <dt><%= Product.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency product.price %></dd>
    </dl>
  </div>
<% end %>
<%= link_to 'Voltar para loja', products_path %>

app/views/products/show.html.erb
<h1>Detalhes do produto</h1>
<% if @product.enable? %>
  <h2>Produto disponivel</h2>
  <% if current_user.profile.present? && @product.profile_id != current_user.profile.id  %>
    <%= link_to 'Comprar produto', new_product_order_path(@product) %>
  <% else %>
    <h2>Seu anuncio</h2>
  <% end %>
<% end %>
<% if @product.disable? %>
  <h2>Esse produto não esta mais disponivel para venda</h2>
<% end %>
  <div>
  <% if @product.image.attached? %>
    <%= image_tag @product.image %>
  <% end %>
</div>
<div>
  <dl>
    <dt><%= Product.human_attribute_name(:category) %></dt>
    <dd><%= @product.category %></dd>
    <dt><%= Product.human_attribute_name(:name) %></dt>
    <dd><%= @product.name %></dd>
    <dt><%= Product.human_attribute_name(:description) %></dt>
    <dd><%= @product.description %></dd>
    <dt><%= Product.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency @product.price %></dd>
    <dt>Vendedor</dt>
    <dd><%= @product.profile.name %></dd>
    <dt>Imagem do produto</dt>
  </dl>


</div>


<div id="comment-product">
  <% @product.comments.each do |comment|%>
    <div class="ac_box_top">
      <div class="ac_box_cont">
        <p>Autor:<%= comment.profile.name %></p>
        <p>Pergunta:  <%= comment.body %></p>
        <% comment.answers.each do |answear| %><br>
          <p>Vendedor: <%= @product.profile.name %></p>
          <p>Resposta: <%= answear.body %></p>
        <% end %>
        <div>
          <% if @product.profile_id == current_user.profile.id  %>
            <%= render partial: 'answers/form', locals:{comment:comment} %>
          <% end %>
        </div>  
      </div>
    </div>
  <% end %>
</div>
<% if current_user.profile.present? %>
  <%= render partial: 'comments/form', locals:{product: @product}%>
<% else %>
  <h3>Para deixar comentarios e fazer compras  é necessario completar seu cadastro</h3>
<% end %>

<%= link_to 'Voltar para loja', products_path %> ||
<%= link_to 'Editar anuncio', edit_product_path(@product) if current_user.id == @product.profile_id %> ||
<%= link_to 'Voltar para meus anuncios', my_products_path %>

app/views/products/status.html.erb
<h2>Confira os detalhes do produto</h2>

<% if @order.product.profile.user_id == current_user.id && @order.waiting? %>
  <%= link_to 'Confirmar venda', accept_order_path(@order), method: :post %>
  <%= link_to 'Cancelar venda', decline_order_path(@order), method: :post %>
<% end %>
<% if @order.waiting? %>
  <h2>Aguardando confirmação do vendedor</h2>
<% end %>

<% if @order.accept?%>
    <h2>Essa venda foi finalizada</h2>
<% end %>
<% if @order.decline? %>
  <h2>Essa venda foi cancelada pelo vendedor</h2>
<% end %>

<h3>Dados do vendedor</h3>
<div>
  <dl>
    <dt><%= Profile.human_attribute_name(:name) %></dt>
    <dd><%= @product.profile.name %></dd>
    <dt><%= Profile.human_attribute_name(:cpf) %></dt>
    <dd><%= @product.profile.cpf %></dd>
    <dt><%= Profile.human_attribute_name(:date_of_birth) %></dt>
    <dd><%= l @product.profile.date_of_birth %></dd>
    <dt><%= Profile.human_attribute_name(:department) %></dt>
    <dd><%= @product.profile.department %></dd>
    <dt><%= Profile.human_attribute_name(:role) %></dt>
    <dd><%= @product.profile.role %></dd>
  </dl>
</div>

<h3>Descrição do produto</h3>
<div>
  <dl>
    <dt><%= Product.human_attribute_name(:category) %></dt>
    <dd><%= @product.category %></dd>
    <dt><%= Product.human_attribute_name(:name) %></dt>
    <dd><%= @product.name %></dd>
    <dt><%= Product.human_attribute_name(:description) %></dt>
    <dd><%= @product.description %></dd>
    <dt><%= Product.human_attribute_name(:price) %></dt>
    <dd><%= number_to_currency @product.price %></dd>
  </dl>
</div>

<h3>Dados do comprador</h3>
<h3></h3>
<div>
  <dl>
    <dt><%= Profile.human_attribute_name(:name) %></dt>
    <dd><%= @order.profile.name %></dd>
    <dt><%= Profile.human_attribute_name(:cpf) %></dt>
    <dd><%= @order.profile.cpf %></dd>
    <dt><%= Profile.human_attribute_name(:date_of_birth) %></dt>
    <dd><%= l @order.profile.date_of_birth %></dd>
    <dt><%= Profile.human_attribute_name(:department) %></dt>
    <dd><%= @order.profile.department %></dd>
    <dt><%= Product.human_attribute_name(:role) %></dt>
    <dd><%= @order.profile.role %></dd>
  </dl>
</div>
<div>
<span>Observação: </span>sp
  <%= @order.body %>
</div><br>
<strong>Chat</strong>
<div id="comment-product">
  <% @order.chats.each do |chat| %>
    <div class="ac_box_top">
      <div class="ac_box_cont">
        <%= "Usuário:  #{chat.profile.name}" %><br>
        <%=  chat.body %><br>
      </div>
    </div>  
  <% end %>
</div>
<div>
  <%= form_with model: [@order, @order.chats.build], local:true do |f| %>
    <div><%= f.label :body, 'Chat' %></div>
    <div><%= f.text_field :body %></div>
    <div><%= f.submit 'Enviar' %></div>
<% end %>
</div>


<%= link_to 'Voltar', my_products_path %>